### ISSUE TITLE
InputShiftRegister.ino all low or all high

### ISSUE THREAD

**Issue by fungreenfox** [WoolseyWorkshop/Article-Adding-Digital-IO-To-Your-Arduino#1]
added InputShiftRegister.ino to an esp32 with 74HC165, and when the push button is in act, all 8 pins goes low, and not only one. So whats wrong ?
Setup:
const unsigned long SamplePeriod = 5000;  // sampling period in milliseconds
// Define Connections to 74HC165
// PL pin 1
const uint8_t ISRLatchPin = 12;
// CE pin 15
int clockEnablePin = 22;
// Q7 pin 7
const uint8_t ISRDataPin = 19;//SER OUT
// CP pin 2
//int clockIn = 18;
const uint8_t ISRClockPin = 18;

**Comment by woolseyj** [comment]
I don't have an ESP32, but I will try to help where I can.

It appears you've made some modifications to the sketch to make it compatible with an ESP32.  Would you mind providing the entire sketch so that I may review it?

**Comment by fungreenfox** [comment]
I did not get email about your reply, so i see this a year after. I have found other way around, so it might not be in my folders anymore.
